name: 'puLL-Merge'
description: puLL-Merge is a github-action to add LLM capabilities to pull-requests in github automatically
inputs:
outputs:
runs:
  using: 'composite'
  steps:
    - id: llm-and-post-message
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
          script: |
            console.log('implement me')
