name: 'puLL-Merge'
description: 'puLL-Merge is a github-action to add LLM capabilities to pull-requests in github automatically'
inputs:
  github_token:
    description: |
      Secret token to push review comments, and
      interact with the repository systematically
    required: true
  openai_api_key:
    description: |
      API key to interact with the OpenAI endpoint
  anthropic_api_key:
    description: |
      API key to interact with the Anthropic endpoint
  debounce_time:
    description: |
      Debounce Time in hours
  amplification:
    description: |
      Amplification factor for the generated text
  filterdiff_args:
    description: |
      Arguments to pass to filterdiff
  openai_models:
    description: |
      selection of models to use for the openai endpoint
  anthropic_models:
    description: |
      selection of models to use for the anthropic endpoint
  bedrock_models:
    description: |
      selection of models to use for the bedrock endpoint
  run_if_private:
    description: |
      run the action even if the repository is private
  debug:
    description: enables debug output for this action
    required: false
  repo:
    description: |
      force the repository to run the action on
    required: false
  owner:
    description: |
      force the owner to run the action on
    required: false
  prnum:
    description: |
      force the pull request number to run the action on
    required: false
  max_tokens:
    description: |
      maximum number of tokens to generate
    required: false
  bedrock_aws_iam_role_arn:
    description: |
      AWS IAM Role ARN to interact with the Bedrock endpoint
    default: ""
  region:
    description: |
      AWS region to interact with the Bedrock endpoint
    default: ""
  include_diff:
    description: |
      Include the diff in the generated text
    required: false
  system_prompt:
    description: |
      Custom system prompt for the LLM. If not provided, uses the default from utils.js
    required: false
# outputs:
runs:
  using: 'composite'
  steps:
    - if: ${{ inputs.bedrock_aws_iam_role_arn != '' && inputs.region != ''}}
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
      with:
        role-to-assume: ${{ inputs.bedrock_aws_iam_role_arn }}
        aws-region: ${{ inputs.region }}
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: '24.x'
    - name: Install patchutils
      run: sudo apt-get install -y patchutils
      shell: bash
    - id: npm
      run: cd ${{ github.action_path }}; npm ci
      shell: bash
    - id: llm-and-post-message
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'CI/skip-llm') && !contains(github.event.pull_request.labels.*.name, 'CI/skip') && github.event.pull_request.draft == false }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        DEBUG: ${{ (inputs.debug == 'true' || runner.debug) && 'true' || 'false'}}
      with:
          script: |
            const actionPath = '${{ github.action_path }}'
            const script = require(`${actionPath}/action.cjs`)
            const inputs = ${{ toJson(inputs) }}
            await script({github, context, inputs, actionPath})
