import { Given, When, Then } from '@cucumber/cucumber'
import { expect } from 'chai'
import fc from 'fast-check'
import { mockState } from '../support/state.mjs'

const countOccurrences = (haystack, needle) => haystack.split(needle).length - 1

const unescape = (text) => text.replace(/\\n/g, '\n').replace(/\\t/g, '\t')

const trimDoc = (doc) => doc.replace(/\n$/, '')

async function callHelper (world) {
  const utils = await import('../../src/utils.js')
  world.calls = []
  world.error = null
  world.result = undefined
  const getResponse = async (prompt, model) => {
    world.calls.push({ prompt, model })
    if (world.errorForModel && world.errorForModel.has(model)) {
      throw new Error(world.errorForModel.get(model))
    }
    if (world.errorForEveryModel) {
      throw new Error(world.errorForEveryModel)
    }
    return world.response
  }
  try {
    world.result = await utils.explainPatchHelper(world.patchBody, world.owner, world.repo, world.models, world.debug, getResponse)
  } catch (err) {
    world.error = err
  }
}

Given('patch body {string}', function (patchBody) {
  this.patchBody = patchBody
})

Given('owner {string} and repo {string}', function (owner, repo) {
  this.owner = owner
  this.repo = repo
})

Given('models {string}', function (models) {
  this.models = models.split(' ').filter(Boolean)
})

Given('models string {string}', function (models) {
  this.models = models
})

Given('an empty model list', function () {
  this.models = []
})

Given('getResponse returns {string}', function (response) {
  this.response = response
})

Given('getResponse returns:', function (doc) {
  this.response = trimDoc(doc)
})

Given('getResponse throws {string} for {string}', function (message, model) {
  this.errorForModel = this.errorForModel || new Map()
  this.errorForModel.set(model, message)
})

Given('getResponse throws {string} for every model', function (message) {
  this.errorForEveryModel = message
})

Given('debug is on', function () {
  this.debug = true
})

When('explainPatchHelper is called', async function () {
  await callHelper(this)
})

Then('it resolves to exactly:', function (doc) {
  expect(this.error).to.equal(null)
  expect(this.result).to.equal(trimDoc(doc))
})

Then('it resolves to exactly {string}', function (expected) {
  expect(this.error).to.equal(null)
  expect(this.result).to.equal(unescape(expected))
})

Then('it rejects with {string}', function (message) {
  expect(this.error).to.be.an('error')
  expect(this.error.message).to.equal(message)
})

Then('it rejects with a TypeError', function () {
  expect(this.error).to.be.an('error')
  expect(this.error).to.be.instanceOf(TypeError)
})

Then('the prompt for call {int} embeds {string}', function (callNumber, fragment) {
  expect(this.calls[callNumber - 1].prompt).to.contain(fragment)
})

Then('the prompt for call {int} embeds today\'s date', function (callNumber) {
  const today = new Date().toISOString().split('T')[0]
  expect(this.calls[callNumber - 1].prompt).to.contain(`Date: ${today}`)
})

Then('the prompt for call {int} embeds the fenced patch body', function (callNumber) {
  const fence = '```\n' + this.patchBody + '\n```'
  expect(this.calls[callNumber - 1].prompt).to.contain(fence)
})

Then('the model for call {int} is {string}', function (callNumber, model) {
  expect(this.calls[callNumber - 1].model).to.equal(model)
})

Then('{int} calls were made', function (count) {
  expect(this.calls).to.have.lengthOf(count)
})

Then('the error {string} was logged', function (message) {
  const logs = mockState().logs
  expect(logs.some((line) => line.includes(message))).to.equal(true)
})

Then('the user prompt was logged', function () {
  const logs = mockState().logs
  expect(logs.some((line) => line.includes('user_prompt:'))).to.equal(true)
  expect(logs.some((line) => line.includes(this.patchBody))).to.equal(true)
})

When('the plain wrap property holds for {int} runs', async function (runs) {
  const utils = await import('../../src/utils.js')
  const safeText = fc.array(fc.constantFrom('a', 'b', 'c', ' ', '.', ',', '\n', '!', '?', '-'), { maxLength: 30 })
    .map((chars) => chars.join(''))
  const model = 'prop-model'
  const patchBody = '+++ prop patch'
  await fc.assert(fc.asyncProperty(safeText, async (text) => {
    const out = await utils.explainPatchHelper(patchBody, 'o', 'r', [model], false, async () => text)
    expect(out).to.equal(`${text}\n</details>\n\n<!-- Generated by ${model} -->`)
  }), { numRuns: runs })
})

When('the mermaid preservation property holds for {int} runs', async function (runs) {
  const utils = await import('../../src/utils.js')
  const safeText = fc.array(fc.constantFrom('a', 'b', 'c', ' ', '.', '\n'), { maxLength: 20 })
    .map((chars) => chars.join(''))
  const diagram = (i) => '```mermaid\ngraph TD;\n  N' + i + '-->M' + i + ';\n```'
  const property = fc.asyncProperty(
    safeText,
    safeText,
    fc.integer({ min: 0, max: 3 }),
    fc.integer({ min: 0, max: 3 }),
    fc.boolean(),
    fc.boolean(),
    async (prefix, suffix, beforeCount, afterCount, hasChanges, hasNext) => {
      const diagrams = []
      for (let i = 0; i < beforeCount + afterCount; i++) diagrams.push(diagram(i))
      const diagramText = (n, offset) => diagrams.slice(offset, offset + n).join('\n\n')
      let response
      if (hasChanges) {
        const next = hasNext ? `\n### Next\n${suffix}` : `\n${suffix}`
        const afterText = afterCount ? diagramText(afterCount, beforeCount) + '\n\n' : ''
        response = `${prefix}\n### Changes\nchange body\n\n${diagramText(beforeCount, 0)}\n\n${afterText}${next}`
      } else {
        response = `${prefix}\n${diagramText(beforeCount + afterCount, 0)}\n${suffix}`
      }
      const model = 'prop-model'
      const out = await utils.explainPatchHelper('+++ p', 'o', 'r', [model], false, async () => response)
      expect(out.endsWith(`\n\n<!-- Generated by ${model} -->`)).to.equal(true)
      expect(countOccurrences(out, '<!-- Generated by ')).to.equal(1)
      expect(countOccurrences(out, '</details>')).to.equal(1)
      for (const d of diagrams) {
        expect(countOccurrences(out, d)).to.equal(1)
      }
      expect(countOccurrences(out, '```mermaid')).to.equal(diagrams.length)
      if (hasChanges) {
        expect(out.indexOf('<details>')).to.be.lessThan(out.indexOf('### Changes'))
      }
    }
  )
  await fc.assert(property, { numRuns: runs })
})

When('the model fallback property holds for {int} runs', async function (runs) {
  const utils = await import('../../src/utils.js')
  const models = fc.uniqueArray(fc.string({ minLength: 1, maxLength: 8 }).filter((s) => !s.includes(' ')), { minLength: 1, maxLength: 5 })
  const property = fc.asyncProperty(models, fc.nat(), async (modelList, failCountRaw) => {
    const failCount = failCountRaw % modelList.length
    const calls = []
    const getResponse = async (prompt, model) => {
      calls.push(model)
      if (calls.length <= failCount) throw new Error('fail ' + model)
      return 'response for ' + model
    }
    const out = await utils.explainPatchHelper('+++ p', 'o', 'r', modelList, false, getResponse)
    expect(calls).to.deep.equal(modelList.slice(0, failCount + 1))
    expect(out.endsWith(`<!-- Generated by ${modelList[failCount]} -->`)).to.equal(true)
  })
  await fc.assert(property, { numRuns: runs })
})
