Feature: action orchestrator
  The GitHub Action entrypoint wires config, properties and inputs into the
  patch retrieval, filtering, explanation and review submission pipeline.
  Options precedence: defaults < repo config file < pull_merge_ properties
  < action inputs. Empty-string inputs are deleted before merging.

  Background:
    Given owner "brave" and repo "pull-merge"
    And pr number 42
    And a github client
    And the patch tokenizes to 100000 tokens
    And the chat response content is "the review"
    And the action PR diff is:
      """
      the diff body
      """
    And the repo is public
    And the PR has these comments:
      | id | body | age_hours |

  Scenario: the happy path reviews a PR with the default openai model
    When the action runs
    Then it resolves to undefined
    And a comment was created with body:
      """
      [[puLL-Merge](https://github.com/brave/pull-merge)] - [brave/pull-merge@42](https://github.com/brave/pull-merge/pull/42)



      the review
      </details>

      <!-- Generated by gpt-5.3-codex -->
      """
    And the puLL-Merge label was added
    And chat request 1 used model "gpt-5.3-codex" temperature 1.0 and max tokens 3072
    And chat request 1 carries the system and user prompts

  Scenario: the DEBUG environment variable turns on logging and an openai debug watermark
    Given the environment variable DEBUG is "true"
    When the action runs
    Then it resolves to undefined
    And the log line "Initializing puLL-Merge" was recorded
    And a log line containing "Using options:" was recorded
    And a log line containing "Using config:" was recorded
    And a log line containing "Using properties:" was recorded
    And a log line containing "Using inputs:" was recorded
    And a comment was created containing "openai debug - [[puLL-Merge]"
    And a comment was created containing "<details><summary>Diff</summary>"
    And the puLL-Merge label was added

  Scenario: an anthropic api key routes to the anthropic provider
    Given the action inputs:
      """
      {"anthropic_api_key": "sk-ant-test", "debug": "true"}
      """
    And the stream response text is "the review"
    When the action runs
    Then 1 stream call was made
    And stream request 1 used model "claude-opus-5" temperature 1.0 and max tokens 3072
    And a comment was created containing "anthropic debug - [[puLL-Merge]"
    And the puLL-Merge label was added

  Scenario: a bedrock role arn routes to bedrock
    Given the action inputs:
      """
      {"bedrock_aws_iam_role_arn": "arn:aws:iam::123:role/pull-merge", "debug": "true"}
      """
    And the bedrock stream yields text "the review"
    When the action runs
    Then bedrock invocation 1 used model "global.anthropic.claude-opus-5-v1:0"
    And a comment was created containing "bedrock debug - [[puLL-Merge]"
    And the puLL-Merge label was added

  Scenario: subtle mode updates the PR description instead of commenting
    Given the action inputs:
      """
      {"subtle_mode": "true"}
      """
    And the PR description:
      """
      """
    When the action runs
    Then it resolves to undefined
    And the PR description was updated to:
      """


      <details><summary>AI Review</summary>

      [[puLL-Merge](https://github.com/brave/pull-merge)] - [brave/pull-merge@42](https://github.com/brave/pull-merge/pull/42)



      the review
      </details>

      <!-- Generated by gpt-5.3-codex --></details>
      """
    And no comment was created
    And the puLL-Merge label was added

  Scenario: a fresh watermark comment debounces the run
    Given the PR has these comments:
      | id | body | age_hours |
      | C1 | [[puLL-Merge](https://github.com/brave/pull-merge)] - [brave/pull-merge@42](https://github.com/brave/pull-merge/pull/42) | 1 |
    When the action runs
    Then it resolves to undefined
    And no comment was created
    And no labels were added

  Scenario: run_if_private without bedrock is an impossible state
    Given the action inputs:
      """
      {"run_if_private": "true"}
      """
    When the action runs
    Then it rejects with "impossible state: should only run on private repositories using bedrock"

  Scenario: a renovate PR author routes to getRenovatePatch
    Given the action context has PR author "renovate[bot]"
    And the action context has actor "renovate[bot]"
    And the PR body:
      """
      This PR contains the following updates:

      | Package | Change |
      |---|---|
      | [pkg](https://redirect.github.com/org/repo) | 1.0.0 -> 1.1.0 |
      """
    And the repo "org/repo" has tags:
      """
      v1.0.0
      v1.1.0
      """
    And the compare diff at "https://github.com/org/repo/compare/v1.0.0..v1.1.0.diff" responds with:
      """
      RENOVATEDIFF
      """
    When the action runs
    Then a comment was created containing "org/repo@v1.0.0..v1.1.0"
    And a comment was created containing "<details><summary>Diff</summary>"
    And a comment was created containing "RENOVATEDIFF"
    And the puLL-Merge label was added

  Scenario: the renovate actor alone routes to getRenovatePatch
    Given the action context has no pull request payload
    And the action context has actor "renovate[bot]"
    And the PR body:
      """
      This PR contains the following updates:

      | Package | Change |
      |---|---|
      | [pkg](https://redirect.github.com/org/repo) | 1.0.0 -> 1.1.0 |
      """
    And the repo "org/repo" has tags:
      """
      v1.0.0
      v1.1.0
      """
    And the compare diff at "https://github.com/org/repo/compare/v1.0.0..v1.1.0.diff" responds with:
      """
      RENOVATEDIFF
      """
    When the action runs
    Then a comment was created containing "org/repo@v1.0.0..v1.1.0"
    And the puLL-Merge label was added

  Scenario: the dependabot actor routes to getDependabotPatch
    Given the action context has PR author "someone"
    And the action context has actor "dependabot[bot]"
    And the PR body:
      """
      Bumps [pkg](https://github.com/org/repo) from 1.0.0 to 1.1.0.
      """
    And the repo "org/repo" has tags:
      """
      v1.0.0
      v1.1.0
      """
    And the compare diff at "https://github.com/org/repo/compare/v1.0.0..v1.1.0.diff" responds with:
      """
      DEPDIFF
      """
    When the action runs
    Then a comment was created containing "org/repo@v1.0.0..v1.1.0"
    And a comment was created containing "<details><summary>Diff</summary>"
    And the puLL-Merge label was added

  Scenario: a dependabot PR author routes to getDependabotPatch
    Given the action context has PR author "dependabot[bot]"
    And the PR body:
      """
      Bumps [pkg](https://github.com/org/repo) from 1.0.0 to 1.1.0.
      """
    And the repo "org/repo" has tags:
      """
      v1.0.0
      v1.1.0
      """
    And the compare diff at "https://github.com/org/repo/compare/v1.0.0..v1.1.0.diff" responds with:
      """
      DEPDIFF
      """
    When the action runs
    Then a comment was created containing "org/repo@v1.0.0..v1.1.0"
    And a comment was created containing "the review"
    And the puLL-Merge label was added

  Scenario: empty string inputs are deleted and fall back to defaults
    Given the action inputs:
      """
      {"openai_models": "", "debug": "true"}
      """
    When the action runs
    Then chat request 1 used model "gpt-5.3-codex" temperature 1.0 and max tokens 3072
    And a log line containing "Using options:" was recorded

  Scenario: errors are swallowed without debug
    Given the action context has no pull request payload
    And no PR comments are routed
    When the action runs
    Then it resolves to undefined
    And a log line containing "fake github: unexpected graphql" was recorded
    And no labels were added

  Scenario: errors are rethrown with debug
    Given the environment variable DEBUG is "true"
    And the action context has no pull request payload
    And no PR comments are routed
    When the action runs
    Then it rejects with an error containing "fake github: unexpected graphql"

  Scenario: config, properties and inputs override in precedence order
    Given a config file ".github/pull-merge.json" containing:
      """
      {"amplification": "5"}
      """
    And repo properties:
      | property_name | value |
      | pull_merge_amplification | 3 |
      | pull_merge_max_tokens | 512 |
    And the action inputs:
      """
      {"max_tokens": "256", "include_diff": "true", "debug": "true"}
      """
    When the action runs
    Then chat request 1 used model "gpt-5.3-codex" temperature 1.0 and max tokens 256
    And a log line containing '"amplification":3' was recorded
    And a comment was created containing "<details><summary>Diff</summary>"
    And the puLL-Merge label was added

  Scenario: subtle mode with a renovate PR raises an unsupported error
    Given the action inputs:
      """
      {"subtle_mode": "true"}
      """
    And the action context has PR author "renovate[bot]"
    When the action runs
    Then it resolves to undefined
    And a log line containing "subtle_mode enabled, this is not supported for renovate" was recorded
    And no labels were added

  Scenario: subtle mode with a dependabot PR raises an unsupported error
    Given the action inputs:
      """
      {"subtle_mode": "true"}
      """
    And the action context has PR author "dependabot[bot]"
    When the action runs
    Then it resolves to undefined
    And a log line containing "subtle_mode enabled, this is not supported for dependabot" was recorded
    And no labels were added

  Scenario: the action options precedence property holds for 15 runs
    When the action options precedence property holds for 15 runs
