Feature: anthropicExplainPatch
  Business rule: patches are explained by Anthropic models through the
  messages stream API. The patch is token-counted before any client is
  built: empty patches are rejected, trivial patches (below
  amplification * max_tokens tokens) return an empty review when
  include_diff asks for inline context and are rejected otherwise.
  Note: unlike the OpenAI variant the token gates run before
  explainPatchHelper, so the trivial include_diff result is a literal
  empty string with no wrapper or model attribution.

  Background:
    Given patch body "+++ a diff"
    And owner "brave" and repo "pull-merge"

  Scenario: explains a patch through the messages stream
    Given the patch tokenizes to 6144 tokens
    And the stream response text is "the review"
    When anthropicExplainPatch is called
    Then it resolves to exactly:
      """
      the review
      </details>

      <!-- Generated by claude-opus-5 -->
      """
    And the Anthropic client was constructed with api key "sk-ant-test"
    And 1 stream call was made
    And stream request 1 used model "claude-opus-5" temperature 1.0 and max tokens 3072
    And stream request 1 carries the system and user prompts

  Scenario: custom parameters reach the stream call
    Given the patch tokenizes to 1024 tokens
    And models "claude-sonnet-4"
    And max tokens 512
    And temperature 0.5
    And api key "sk-custom"
    And the stream response text is "custom review"
    When anthropicExplainPatch is called
    Then it resolves to exactly:
      """
      custom review
      </details>

      <!-- Generated by claude-sonnet-4 -->
      """
    And the Anthropic client was constructed with api key "sk-custom"
    And stream request 1 used model "claude-sonnet-4" temperature 0.5 and max tokens 512

  Scenario: empty patches are rejected
    Given the patch tokenizes to 0 tokens
    When anthropicExplainPatch is called
    Then it rejects with "The patch is empty, cannot summarize!"
    And no Anthropic client was constructed
    And 0 stream calls were made

  Scenario: trivial patches are rejected without include_diff
    Given max tokens 100
    And the patch tokenizes to 199 tokens
    When anthropicExplainPatch is called
    Then it rejects with "The patch is trivial, no need for a summarization"
    And no Anthropic client was constructed
    And 0 stream calls were made

  Scenario: trivial patches return an empty review with include_diff
    Given max tokens 100
    And the patch tokenizes to 199 tokens
    And include_diff is on
    When anthropicExplainPatch is called
    Then it resolves to exactly ""
    And no Anthropic client was constructed
    And 0 stream calls were made

  Scenario: debug logs the stream response
    Given the patch tokenizes to 6144 tokens
    And the stream response text is "the review"
    And debug is on
    When anthropicExplainPatch is called
    Then the stream response was logged

  Scenario: model failures fall back to the next model
    Given the patch tokenizes to 6144 tokens
    And models "claude-a claude-b"
    And the stream fails on the first 1 calls with "boom"
    And the stream response text is "recovered review"
    When anthropicExplainPatch is called
    Then it resolves to exactly:
      """
      recovered review
      </details>

      <!-- Generated by claude-b -->
      """
    And 2 stream calls were made

  Scenario: stream errors on the last model are rethrown
    Given the patch tokenizes to 6144 tokens
    And models "claude-a"
    And the stream fails with "kaput"
    When anthropicExplainPatch is called
    Then it rejects with "kaput"
    And 1 stream call was made

  @property
  Scenario: the patch body reaches the model verbatim
    For any patch body the user prompt embeds the diff in a fenced
    block and the review is attributed to the model that answered.
    When the anthropic patch embedding property holds for 25 runs
