Feature: bedrockExplainPatch
  Explains a patch using Amazon Bedrock with streaming responses.
  Token gates run inside the model callback (openai semantics): a trivial
  patch with include_diff returns the empty wrapper wrapped by the helper.
  SSM Parameter Store provides an optional inference profile ARN that
  overrides the model id on the InvokeModel command.

  Background:
    Given patch body "diff --git a/x b/x"
    And owner "brave" and repo "pull-merge"
    And the patch tokenizes to 100000 tokens

  Scenario: default parameters invoke bedrock with the standard payload
    Given the bedrock stream yields text "Hello world"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hello world
      </details>

      <!-- Generated by global.anthropic.claude-opus-5-v1:0 -->
      """
    And 1 bedrock invocation was made
    And the Bedrock clients were constructed for region "us-east-1"
    And the SSM parameter "/pull-merge/inference-profile-arn" was requested
    And bedrock invocation 1 used model "global.anthropic.claude-opus-5-v1:0"
    And bedrock invocation 1 used max tokens 3072 and temperature 1.0
    And bedrock invocation 1 carries the system and user prompts

  Scenario: an SSM inference profile overrides the model id
    Given an SSM inference profile "arn:aws:bedrock:us-east-1::inference-profile/opus5"
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then bedrock invocation 1 used model "arn:aws:bedrock:us-east-1::inference-profile/opus5"

  Scenario: debug logs the inference profile ARN in use
    Given an SSM inference profile "arn:aws:bedrock:us-east-1::inference-profile/opus5"
    And the bedrock stream yields text "Hi"
    And debug is on
    When bedrockExplainPatch is called
    Then a log line containing "Using inference profile ARN: arn:aws:bedrock:us-east-1::inference-profile/opus5" was recorded
    And a log line containing "full text:" was recorded

  Scenario: an SSM failure continues without an inference profile
    Given the SSM parameter store fails with "parameter not found"
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hi
      </details>

      <!-- Generated by global.anthropic.claude-opus-5-v1:0 -->
      """
    And bedrock invocation 1 used model "global.anthropic.claude-opus-5-v1:0"

  Scenario: debug logs the SSM failure
    Given the SSM parameter store fails with "parameter not found"
    And the bedrock stream yields text "Hi"
    And debug is on
    When bedrockExplainPatch is called
    Then a log line containing "Failed to retrieve inference profile ARN: parameter not found" was recorded

  Scenario: an empty patch is rejected before any invocation
    Given the patch tokenizes to 0 tokens
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then it rejects with "The patch is empty, cannot summarize!"
    And 0 bedrock invocations were made

  Scenario: a trivial patch is rejected
    Given the patch tokenizes to 199 tokens
    And max tokens 100
    When bedrockExplainPatch is called
    Then it rejects with "The patch is trivial, no need for a summarization"
    And 0 bedrock invocations were made

  Scenario: a trivial patch with include_diff returns the empty wrapper
    Given the patch tokenizes to 199 tokens
    And max tokens 100
    And include_diff is on
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """

      </details>

      <!-- Generated by global.anthropic.claude-opus-5-v1:0 -->
      """

  Scenario: a model without a token counting function is rejected
    Given models "amazon.titan-text-express-v1"
    When bedrockExplainPatch is called
    Then it rejects with "Model amazon.titan-text-express-v1 not supported for token counting"
    And 0 bedrock invocations were made

  Scenario: non-text events and malformed chunks are ignored
    Given the bedrock stream yields the events:
      """
      {"type":"message_start"}
      {"type":"content_block_delta"}
      {"type":"content_block_delta","delta":{"type":"input_json_delta"}}
      {broken}
      {"type":"content_block_delta","delta":{"type":"text_delta","text":"Hello"}}
      {"type":"message_stop"}
      """
    And the bedrock stream includes an invalid chunk
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hello
      </details>

      <!-- Generated by global.anthropic.claude-opus-5-v1:0 -->
      """

  Scenario: debug logs skipped non-JSON lines and stop reasons
    Given the bedrock stream yields the events:
      """
      {"type":"content_block_delta","delta":{"type":"text_delta","text":"Hi"}}
      {broken}
      {"type":"message_stop"}
      """
    And debug is on
    When bedrockExplainPatch is called
    Then a log line containing "skipping non-JSON line" was recorded
    And a log line containing "stop reason:" was recorded

  Scenario: a stream without text deltas produces no text
    Given the bedrock stream yields the events:
      """
      {"type":"message_start"}
      {"type":"message_stop"}
      """
    When bedrockExplainPatch is called
    Then it rejects with "Bedrock stream produced no text"

  Scenario: a stream failure surfaces as a wrapped error with a cause
    Given the bedrock stream fails with "network down"
    When bedrockExplainPatch is called
    Then it rejects with "Bedrock stream failed"
    And the failure was caused by the stream error

  Scenario: a failing model falls back to the next supported model
    Given models "global.anthropic.claude-opus-5-v1:0 global.anthropic.claude-sonnet-5-v1:0"
    And the bedrock stream fails on the first 1 calls with "throttled"
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hi
      </details>

      <!-- Generated by global.anthropic.claude-sonnet-5-v1:0 -->
      """
    And 2 bedrock invocations were made
    And bedrock invocation 1 used model "global.anthropic.claude-opus-5-v1:0"
    And bedrock invocation 2 used model "global.anthropic.claude-sonnet-5-v1:0"

  Scenario: an unsupported model falls back to a supported one
    Given models "not.a.model global.anthropic.claude-opus-5-v1:0"
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hi
      </details>

      <!-- Generated by global.anthropic.claude-opus-5-v1:0 -->
      """
    And 1 bedrock invocation was made

  Scenario: custom region and generation parameters are honored
    Given region "eu-west-1"
    And models "global.anthropic.claude-sonnet-5-v1:0"
    And max tokens 512
    And temperature 0.5
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then the Bedrock clients were constructed for region "eu-west-1"
    And bedrock invocation 1 used model "global.anthropic.claude-sonnet-5-v1:0"
    And bedrock invocation 1 used max tokens 512 and temperature 0.5

  Scenario: the bedrock patch embedding property holds for 25 runs
    When the bedrock patch embedding property holds for 25 runs
