Feature: bedrockExplainPatch
  Explains a patch using Amazon Bedrock with streaming responses.
  Token gates run inside the model callback (openai semantics): a trivial
  patch with include_diff returns the empty wrapper wrapped by the helper.
  SSM Parameter Store provides an optional inference profile ARN that
  overrides the model id on the InvokeModel command.

  Background:
    Given patch body "diff --git a/x b/x"
    And owner "brave" and repo "pull-merge"
    And the patch tokenizes to 100000 tokens

  Scenario: default parameters invoke bedrock with the standard payload
    Given the bedrock stream yields text "Hello world"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hello world

      <!-- Generated by global.anthropic.claude-opus-5-5-v1:0 -->
      """
    And 1 bedrock invocation was made
    And the Bedrock clients were constructed for region "us-east-1"
    And the SSM parameter "/pull-merge/inference-profile-arn" was requested
    And bedrock invocation 1 used model "global.anthropic.claude-opus-5-5-v1:0"
    And bedrock invocation 1 used max tokens 16384 and temperature 1.0
    And bedrock invocation 1 carries the system and user prompts

  Scenario: an SSM inference profile overrides the model id
    Given an SSM inference profile "arn:aws:bedrock:us-east-1::inference-profile/opus5"
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then bedrock invocation 1 used model "arn:aws:bedrock:us-east-1::inference-profile/opus5"

  Scenario: debug logs the inference profile ARN in use
    Given an SSM inference profile "arn:aws:bedrock:us-east-1::inference-profile/opus5"
    And the bedrock stream yields text "Hi"
    And debug is on
    When bedrockExplainPatch is called
    Then a log line containing "Using inference profile ARN: arn:aws:bedrock:us-east-1::inference-profile/opus5" was recorded
    And a log line containing "full text:" was recorded

  Scenario: an SSM failure continues without an inference profile
    Given the SSM parameter store fails with "parameter not found"
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hi

      <!-- Generated by global.anthropic.claude-opus-5-5-v1:0 -->
      """
    And bedrock invocation 1 used model "global.anthropic.claude-opus-5-5-v1:0"

  Scenario: debug logs the SSM failure
    Given the SSM parameter store fails with "parameter not found"
    And the bedrock stream yields text "Hi"
    And debug is on
    When bedrockExplainPatch is called
    Then a log line containing "Failed to retrieve inference profile ARN: parameter not found" was recorded

  Scenario: an empty patch is rejected before any invocation
    Given the patch tokenizes to 0 tokens
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then it rejects with "The patch is empty, cannot summarize!"
    And 0 bedrock invocations were made

  Scenario: a trivial patch is rejected
    Given the patch tokenizes to 199 tokens
    And max tokens 100
    When bedrockExplainPatch is called
    Then it rejects with "The patch is trivial, no need for a summarization"
    And 0 bedrock invocations were made

  Scenario: a trivial patch with include_diff returns the empty wrapper
    Given the patch tokenizes to 199 tokens
    And max tokens 100
    And include_diff is on
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """


      <!-- Generated by global.anthropic.claude-opus-5-5-v1:0 -->
      """

  Scenario: a model without a token counting function is rejected
    Given models "amazon.titan-text-express-v1"
    When bedrockExplainPatch is called
    Then it rejects with "Model amazon.titan-text-express-v1 not supported for token counting"
    And 0 bedrock invocations were made

  Scenario: non-text events and malformed chunks are ignored
    Given the bedrock stream yields the events:
      """
      {"type":"message_start"}
      {"type":"content_block_delta"}
      {"type":"content_block_delta","delta":{"type":"input_json_delta"}}
      {broken}
      {"type":"content_block_delta","delta":{"type":"text_delta","text":"Hello"}}
      {"type":"message_delta","delta":{"stop_reason":"end_turn"}}
      {"type":"message_stop"}
      """
    And the bedrock stream includes an invalid chunk
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hello

      <!-- Generated by global.anthropic.claude-opus-5-5-v1:0 -->
      """

  Scenario: debug logs skipped non-JSON lines and stop reasons
    Given the bedrock stream yields the events:
      """
      {"type":"content_block_delta","delta":{"type":"text_delta","text":"Hi"}}
      {broken}
      {"type":"message_delta","delta":{"stop_reason":"end_turn"}}
      {"type":"message_stop"}
      """
    And debug is on
    When bedrockExplainPatch is called
    Then a log line containing "skipping non-JSON line" was recorded
    And a log line containing "stop reason:" was recorded

  Scenario: a stream without text deltas produces no text
    Given the bedrock stream yields the events:
      """
      {"type":"message_start"}
      {"type":"message_delta","delta":{"stop_reason":"end_turn"}}
      {"type":"message_stop"}
      """
    When bedrockExplainPatch is called
    Then it rejects with "Bedrock stream produced no text"

  Scenario: a stream that ends without a stop reason is rejected
    Given the bedrock stream yields the events:
      """
      {"type":"content_block_delta","delta":{"type":"text_delta","text":"partial review"}}
      """
    When bedrockExplainPatch is called
    Then it rejects with "Bedrock stream ended without a stop reason"

  Scenario: a mid-stream error event is rejected
    Given the bedrock stream yields the events:
      """
      {"type":"content_block_delta","delta":{"type":"text_delta","text":"partial review"}}
      {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}
      """
    When bedrockExplainPatch is called
    Then it rejects with "Bedrock stream error event: {\"type\":\"error\",\"error\":{\"type\":\"overloaded_error\",\"message\":\"Overloaded\"}}"

  Scenario: an output-token cap clamps the retry budget
    Given the patch tokenizes to 100000 tokens
    And the first bedrock call rejects the token budget with "max_tokens: Input should be at most 8192"
    And the bedrock stream yields text "the review"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      the review

      <!-- Generated by global.anthropic.claude-opus-5-5-v1:0 -->
      """
    And 2 bedrock invocations were made
    And bedrock invocation 1 used max tokens 16384 and temperature 1.0
    And bedrock invocation 2 used max tokens 8192 and temperature 1.0

  Scenario: a stream failure surfaces as a wrapped error with a cause
    Given the bedrock stream fails with "network down"
    When bedrockExplainPatch is called
    Then it rejects with "Bedrock stream failed"
    And the failure was caused by the stream error

  Scenario: a failing model falls back to the next supported model
    Given models "global.anthropic.claude-opus-5-5-v1:0 global.anthropic.claude-sonnet-5-v1:0"
    And the bedrock stream fails on the first 1 calls with "throttled"
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hi

      <!-- Generated by global.anthropic.claude-sonnet-5-v1:0 -->
      """
    And 2 bedrock invocations were made
    And bedrock invocation 1 used model "global.anthropic.claude-opus-5-5-v1:0"
    And bedrock invocation 2 used model "global.anthropic.claude-sonnet-5-v1:0"

  Scenario: an unsupported model falls back to a supported one
    Given models "not.a.model global.anthropic.claude-opus-5-5-v1:0"
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hi

      <!-- Generated by global.anthropic.claude-opus-5-5-v1:0 -->
      """
    And 1 bedrock invocation was made

  Scenario: custom region and generation parameters are honored
    Given region "eu-west-1"
    And models "global.anthropic.claude-sonnet-5-v1:0"
    And max tokens 512
    And temperature 0.5
    And the bedrock stream yields text "Hi"
    When bedrockExplainPatch is called
    Then the Bedrock clients were constructed for region "eu-west-1"
    And bedrock invocation 1 used model "global.anthropic.claude-sonnet-5-v1:0"
    And bedrock invocation 1 used max tokens 512 and temperature 0.5

  Scenario: the model marker embeds the reviewed commit sha
    Given the bedrock stream yields text "Hi"
    And the head sha is "abc1234"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      Hi

      <!-- Generated by global.anthropic.claude-opus-5-5-v1:0 @ abc1234 -->
      """

  Scenario: a truncated bedrock response retries with doubled max tokens
    Given the patch tokenizes to 100000 tokens
    And the first bedrock call truncates with text "half a review"
    And the bedrock stream yields text "the full review"
    When bedrockExplainPatch is called
    Then it resolves to exactly:
      """
      the full review

      <!-- Generated by global.anthropic.claude-opus-5-5-v1:0 -->
      """
    And 2 bedrock invocations were made
    And bedrock invocation 1 used max tokens 16384 and temperature 1.0
    And bedrock invocation 2 used max tokens 32768 and temperature 1.0

  Scenario: a doubly truncated bedrock response is rejected
    Given the patch tokenizes to 100000 tokens
    And every bedrock call truncates with text "half a review"
    When bedrockExplainPatch is called
    Then it rejects with "Review response truncated at 32768 output tokens (stop_reason=max_tokens)"
    And 2 bedrock invocations were made

  Scenario: the bedrock patch embedding property holds for 25 runs
    When the bedrock patch embedding property holds for 25 runs
