Feature: openaiExplainPatch
  Business rule: patches are explained by OpenAI chat models. The patch
  is token-counted first: empty patches are rejected, trivial patches
  (below amplification * max_tokens tokens) are only summarized when
  include_diff asks for inline context. Models that are not chat models
  answer 404 invalid_request_error and fall back to the legacy
  completions endpoint; every other API error is rethrown.

  Background:
    Given patch body "+++ a diff"
    And owner "brave" and repo "pull-merge"
    And models "test-model"

  Scenario: explains a patch through the chat endpoint
    Given the patch tokenizes to 6144 tokens
    And the chat response content is "the review"
    When openaiExplainPatch is called
    Then it resolves to exactly:
      """
      the review
      </details>

      <!-- Generated by test-model -->
      """
    And the OpenAI client was constructed with api key "sk-test"
    And 1 chat completion was called
    And 0 legacy completions were called
    And chat request 1 used model "test-model" temperature 1.0 and max tokens 3072
    And chat request 1 carries the system and user prompts

  Scenario: debug logs the user prompt and chat response
    Given the patch tokenizes to 6144 tokens
    And the chat response content is "the review"
    And debug is on
    When openaiExplainPatch is called
    Then the user prompt was logged
    And the chat response was logged

  Scenario: empty patches are rejected
    Given the patch tokenizes to 0 tokens
    When openaiExplainPatch is called
    Then it rejects with "The patch is empty, cannot summarize!"
    And 0 chat completions were called

  Scenario: trivial patches are rejected without include_diff
    Given max tokens 100
    And the patch tokenizes to 199 tokens
    When openaiExplainPatch is called
    Then it rejects with "The patch is trivial, no need for a summarization"
    And 0 chat completions were called

  Scenario: trivial patches return an empty review with include_diff
    Given max tokens 100
    And the patch tokenizes to 199 tokens
    And include_diff is on
    When openaiExplainPatch is called
    Then it resolves to exactly:
      """

      </details>

      <!-- Generated by test-model -->
      """
    And 0 chat completions were called

  Scenario: unknown models fall back to the cl100k_base encoding
    Given the patch tokenizes to 6144 tokens
    And the chat response content is "the review"
    And the model is unknown to tiktoken
    When openaiExplainPatch is called
    Then the cl100k_base fallback encoding was requested
    And it resolves to exactly:
      """
      the review
      </details>

      <!-- Generated by test-model -->
      """

  Scenario: legacy completions fallback for non-chat models
    Given the patch tokenizes to 6144 tokens
    And the chat endpoint fails with status 404 type "invalid_request_error" and message "model not found"
    And the legacy completion response text is "legacy review"
    When openaiExplainPatch is called
    Then it resolves to exactly:
      """
      legacy review
      </details>

      <!-- Generated by test-model -->
      """
    And 1 chat completion was called
    And 1 legacy completion was called
    And legacy request 1 prompts with the system prompt and the patch body

  Scenario: debug logs the legacy response
    Given the patch tokenizes to 6144 tokens
    And the chat endpoint fails with status 404 type "invalid_request_error" and message "model not found"
    And the legacy completion response text is "legacy review"
    And debug is on
    When openaiExplainPatch is called
    Then the legacy response was logged

  Scenario: other API errors are rethrown
    Given the patch tokenizes to 6144 tokens
    And the chat endpoint fails with status 500 and message "server exploded"
    When openaiExplainPatch is called
    Then it rejects with "server exploded"
    And 0 legacy completions were called

  Scenario: 404 errors without invalid_request_error are rethrown
    Given the patch tokenizes to 6144 tokens
    And the chat endpoint fails with status 404 type "server_error" and message "still not found"
    When openaiExplainPatch is called
    Then it rejects with "still not found"
    And 0 legacy completions were called

  @property
  Scenario: the patch body reaches the model verbatim
    For any patch body the user prompt embeds the diff in a fenced
    block and the review is attributed to the model that answered.
    When the patch embedding property holds for 25 runs
