Feature: submitReview
  Posts an AI explanation of a PR patch as a PR comment. Skips posting
  (debounces) when a watermark comment fresher than the debounce time
  exists, and deletes stale watermark comments before posting a new one.
  A watermark comment whose "Generated by" marker embeds the current
  head commit sha is never deleted nor re-posted.

  Background:
    Given owner "brave" and repo "pull-merge"
    And pr number 42
    And watermark "wm-1"
    And debounce time 6 hours

  Scenario: rejects a call without a github client or token
    When submitReview is called
    Then it rejects with "You must provide a githubToken to use this function"

  Scenario: constructs an Octokit client from a token and posts the default stub explanation
    Given a github token "ghp_test"
    And the PR has these comments:
      | id | body  | age_hours |
      | C1  | lgtm  | 48        |
    When submitReview is called
    Then an Octokit client was constructed with auth "ghp_test"
    And a comment was created with body:
      """
      wm-1



      no explanation provided<!-- Generated by STUB -->
      """

  Scenario: prefers an injected github client over a token
    Given a github token "ghp_test"
    And a github client
    And the PR has these comments:
      | id | body  | age_hours |
      | C1  | lgtm  | 48        |
    When submitReview is called
    Then no Octokit client was constructed
    And a comment was created with body:
      """
      wm-1



      no explanation provided<!-- Generated by STUB -->
      """

  Scenario: debounces on a fresh watermark comment
    Given a github client
    And the PR has these comments:
      | id | body                   | age_hours |
      | C1  | review: wm-1 done      | 0         |
      | C2  | lgtm                   | 1         |
    When submitReview is called
    Then it returns true
    And no comment was created
    And comment "C1" was not deleted

  Scenario: deletes a stale watermark comment and posts the review
    Given a github client
    And the PR has these comments:
      | id | body                   | age_hours |
      | C1  | review: wm-1 done      | 48        |
      | C2  | lgtm                   | 1         |
    And the explanation callback returns:
      """
      All good<!-- Generated by m1 -->
      """
    When submitReview is called
    Then it returns undefined
    And comment "C1" was deleted
    And comment "C2" was not deleted
    And a comment was created with body:
      """
      wm-1



      All good<!-- Generated by m1 -->
      """

  Scenario: composes the header into the comment body
    Given a github client
    And the PR has these comments:
      | id | body                   | age_hours |
      | C1  | review: wm-1 done      | 48        |
    And header:
      """
      ## AI Review
      """
    And the explanation callback returns:
      """
      All good<!-- Generated by m1 -->
      """
    When submitReview is called
    Then a comment was created with body:
      """
      wm-1

      ## AI Review

      All good<!-- Generated by m1 -->
      """

  Scenario: skips commenting when the explanation is empty
    Given a github client
    And the PR has these comments:
      | id | body                   | age_hours |
      | C1  | review: wm-1 done      | 48        |
    And the explanation callback returns nothing
    When submitReview is called
    Then no comment was created
    And comment "C1" was deleted

  Scenario: logs debug output on the debounce path
    Given a github client
    And debug is on
    And the PR has these comments:
      | id | body                   | age_hours |
      | C1  | review: wm-1 done      | 0         |
    When submitReview is called
    Then the error "submitReview brave pull-merge 42" was logged
    And the error "debounced" was logged

  Scenario: logs debug output on the deletion path
    Given a github client
    And debug is on
    And the PR has these comments:
      | id | body                   | age_hours |
      | C1  | review: wm-1 done      | 48        |
      | C2  | lgtm                   | 1         |
    When submitReview is called
    Then the error "Deleting 2 message(s)" was logged

  Scenario: future-dated watermark comments always debounce
    When the submitReview debounce property holds for 25 runs

  Scenario: sufficiently old watermark comments always re-submit
    When the submitReview re-submission property holds for 25 runs

  Scenario: skips re-commenting when the watermark comment already reviewed the same commit
    Given a github client
    And the head sha is "deadbeef"
    And the PR has these comments:
      | id | body                                              | age_hours |
      | C1  | review: wm-1<!-- Generated by m1 @ deadbeef -->  | 48        |
    When submitReview is called
    Then it returns true
    And no comment was created
    And comment "C1" was not deleted

  Scenario: re-comments when the watermark comment reviewed a different commit
    Given a github client
    And the head sha is "abc1234"
    And the PR has these comments:
      | id | body                                              | age_hours |
      | C1  | review: wm-1<!-- Generated by m1 @ deadbeef -->  | 48        |
    And the explanation callback returns:
      """
      All good<!-- Generated by m1 -->
      """
    When submitReview is called
    Then it returns undefined
    And comment "C1" was deleted
    And a comment was created with body:
      """
      wm-1



      All good<!-- Generated by m1 -->
      """

  Scenario: re-comments on legacy watermark comments without a commit marker
    Given a github client
    And the head sha is "abc1234"
    And the PR has these comments:
      | id | body              | age_hours |
      | C1  | review: wm-1 done | 48        |
    When submitReview is called
    Then it returns undefined
    And comment "C1" was deleted
    And a comment was created with body:
      """
      wm-1



      no explanation provided<!-- Generated by STUB -->
      """

  Scenario: a fresh same-commit comment still debounces
    Given a github client
    And debug is on
    And the head sha is "deadbeef"
    And the PR has these comments:
      | id | body                                              | age_hours |
      | C1  | review: wm-1<!-- Generated by m1 @ deadbeef -->  | 0         |
    When submitReview is called
    Then it returns true
    And the error "debounced" was logged
    And the error "already reviewed commit deadbeef" was not logged

  Scenario: logs debug output on the same-commit skip path
    Given a github client
    And debug is on
    And the head sha is "deadbeef"
    And the PR has these comments:
      | id | body                                              | age_hours |
      | C1  | review: wm-1<!-- Generated by m1 @ deadbeef -->  | 48        |
    When submitReview is called
    Then the error "already reviewed commit deadbeef" was logged

  Scenario: matches the first commit marker and does not overmatch later markers
    Given a github client
    And debug is on
    And the head sha is "deadbeef"
    And the PR has these comments:
      | id | body                                                                                        | age_hours |
      | C1  | review: wm-1<!-- Generated by m1 @ deadbeef --> quoted: <!-- Generated by m2 @ abc1234 --> | 48        |
    When submitReview is called
    Then it returns true
    And the error "already reviewed commit deadbeef" was logged

  @property
  Scenario: the same-commit skip property holds
    When the submitReview same-commit skip property holds for 25 runs
