Feature: subtleSubmitReview
  Updates the PR description in place with the AI review wrapped in a
  <details> block instead of posting a comment. Debounces when the
  description already contains the watermark, and replaces a previous
  review block when present.

  Known behavior: the PR query selects only id and body, so updatedAt is
  undefined and any description containing the watermark throws a
  debounce error regardless of the debounce time. A review block whose
  "Generated by" marker embeds the current head commit sha is never
  rewritten, so the same-commit check runs before the debounce check.

  Background:
    Given owner "brave" and repo "pull-merge"
    And pr number 42
    And watermark "wm-1"
    And debounce time 6 hours

  Scenario: rejects a call without a github client or token
    When subtleSubmitReview is called
    Then it rejects with "You must provide a githubToken to use this function"

  Scenario: constructs an Octokit client from a token and appends the review to the PR description
    Given a github token "ghp_test"
    And the PR description:
      """
      Original description
      """
    And the explanation callback returns:
      """
      All good<!-- Generated by m1 -->
      """
    When subtleSubmitReview is called
    Then an Octokit client was constructed with auth "ghp_test"
    And the PR description was updated to:
      """
      Original description

      <details><summary>AI Review</summary>

wm-1



All good<!-- Generated by m1 --></details>
      """

  Scenario: replaces a review block that appears on the second fetch
    Given a github client
    And the PR description:
      """
      My description
      """
    And the PR description is then:
      """
      My description

      <details><summary>AI Review</summary>

wm-1



OLD<!-- Generated by oldmodel --></details>
      """
    And the explanation callback returns:
      """
      All good<!-- Generated by m1 -->
      """
    When subtleSubmitReview is called
    Then the PR description was updated to:
      """
      My description

      <details><summary>AI Review</summary>

wm-1



All good<!-- Generated by m1 --></details>
      """

  Scenario: throws debounce when the description contains the watermark and updatedAt is unknown
    Given a github client
    And the PR description:
      """
      Some change wm-1 and more text
      """
    When subtleSubmitReview is called
    Then it rejects with "debounce"

  Scenario: proceeds when the watermark is older than the debounce time
    Given a github client
    And the PR description:
      """
      My description

      <details><summary>AI Review</summary>

wm-1



OLD<!-- Generated by oldmodel --></details>
      """
    And the PR description was last updated 48 hours ago
    And the explanation callback returns:
      """
      All good<!-- Generated by m1 -->
      """
    When subtleSubmitReview is called
    Then the PR description was updated to:
      """
      My description

      <details><summary>AI Review</summary>

wm-1



All good<!-- Generated by m1 --></details>
      """

  Scenario: uses the default stub explanation when none is provided
    Given a github client
    And the PR description:
      """
      Original description
      """
    When subtleSubmitReview is called
    Then the PR description was updated to:
      """
      Original description

      <details><summary>AI Review</summary>

wm-1



no explanation provided<!-- Generated by STUB --></details>
      """

  Scenario: logs debug output
    Given a github client
    And debug is on
    And the PR description:
      """
      Original description
      """
    When subtleSubmitReview is called
    Then the error "submitReview brave pull-merge 42" was logged

  Scenario: review replacement preserves surrounding text
    When the review replacement property holds for 25 runs

  Scenario: skips the description update when the review block matches the head commit
    Given a github client
    And the head sha is "deadbeef"
    And the PR description:
      """
      My description

      <details><summary>AI Review</summary>

wm-1



OLD<!-- Generated by oldmodel @ deadbeef --></details>
      """
    And the explanation callback returns:
      """
      All good<!-- Generated by m1 -->
      """
    When subtleSubmitReview is called
    Then it returns true
    And the PR description was not updated
    And the explanation callback was not called

  Scenario: updates the block when it reviewed a different commit
    Given a github client
    And the head sha is "abc1234"
    And the PR description:
      """
      My description

      <details><summary>AI Review</summary>

wm-1



OLD<!-- Generated by oldmodel @ deadbeef --></details>
      """
    And the PR description was last updated 48 hours ago
    And the explanation callback returns:
      """
      All good<!-- Generated by m1 @ abc1234 -->
      """
    When subtleSubmitReview is called
    Then the PR description was updated to:
      """
      My description

      <details><summary>AI Review</summary>

wm-1



All good<!-- Generated by m1 @ abc1234 --></details>
      """

  Scenario: replaces only the first review block without consuming content between duplicates
    Given a github client
    And the head sha is "abc1234"
    And the PR description:
      """
      Intro

      <details><summary>AI Review</summary>

wm-1



OLD1<!-- Generated by oldmodel @ deadbeef --></details>

      Middle text

      <details><summary>AI Review</summary>

wm-1



OLD2<!-- Generated by oldmodel @ abc1234 --></details>

      Outro
      """
    And the PR description was last updated 48 hours ago
    And the explanation callback returns:
      """
      NEW<!-- Generated by m1 @ abc1234 -->
      """
    When subtleSubmitReview is called
    Then the PR description was updated to:
      """
      Intro

      <details><summary>AI Review</summary>

wm-1



NEW<!-- Generated by m1 @ abc1234 --></details>

      Middle text

      <details><summary>AI Review</summary>

wm-1



OLD2<!-- Generated by oldmodel @ abc1234 --></details>

      Outro
      """

  Scenario: logs debug output on the same-commit skip path
    Given a github client
    And debug is on
    And the head sha is "deadbeef"
    And the PR description:
      """
      My description

      <details><summary>AI Review</summary>

wm-1



OLD<!-- Generated by oldmodel @ deadbeef --></details>
      """
    When subtleSubmitReview is called
    Then the error "already reviewed commit deadbeef" was logged
