Feature: explainPatchHelper response shaping
  Business rule: raw model responses become review comments. Mermaid
  diagrams are hoisted into the Changes details block, C4/Sequence
  headers are stripped and every output is signed with the model that
  produced it.

  Background:
    Given patch body "+++ diff --git a/x b/x"
    And owner "myorg" and repo "myrepo"

  Scenario: plain review text gets a closing details tag and model marker
    Given models "model-a"
    And getResponse returns:
      """
      Short review text.
      """
    When explainPatchHelper is called
    Then it resolves to exactly:
      """
      Short review text.
      </details>

      <!-- Generated by model-a -->
      """

  Scenario: user prompt embeds repo, date and the fenced patch
    Given models "model-a"
    And getResponse returns "ok"
    When explainPatchHelper is called
    Then the prompt for call 1 embeds "https://github.com/myorg/myrepo"
    And the prompt for call 1 embeds today's date
    And the prompt for call 1 embeds the fenced patch body
    And the model for call 1 is "model-a"

  Scenario: changes section followed by another section
    Given models "model-a"
    And getResponse returns:
      """
      ### Description
      some text

      ### Changes
      - did thing

      ```mermaid
      graph TD;
        A-->B;
      ```

      ### Security Hotspots
      none
      """
    When explainPatchHelper is called
    Then it resolves to exactly:
      """
      ### Description
      some text

      <details>
      <summary><i>Changes</i></summary>

      ### Changes
      - did thing



      ```mermaid
      graph TD;
        A-->B;
      ```
      </details>

      ### Security Hotspots
      none

      <!-- Generated by model-a -->
      """

  Scenario: changes section at the end of the response
    Given models "model-a"
    And getResponse returns:
      """
      ### Description
      text

      ### Changes
      - did thing

      ```mermaid
      graph TD;
        A-->B;
      ```
      """
    When explainPatchHelper is called
    Then it resolves to exactly:
      """
      ### Description
      text

      <details>
      <summary><i>Changes</i></summary>

      ### Changes
      - did thing

      ```mermaid
      graph TD;
        A-->B;
      ```
      </details>

      <!-- Generated by model-a -->
      """

  Scenario: multiple diagrams are hoisted in order
    Given models "model-a"
    And getResponse returns:
      """
      ### Changes
      - a

      ```mermaid
      graph TD;
        A1-->B1;
      ```

      ```mermaid
      graph TD;
        A2-->B2;
      ```

      ### Description
      end
      """
    When explainPatchHelper is called
    Then it resolves to exactly:
      """
      <details>
      <summary><i>Changes</i></summary>

      ### Changes
      - a





      ```mermaid
      graph TD;
        A1-->B1;
      ```
      ```mermaid
      graph TD;
        A2-->B2;
      ```
      </details>

      ### Description
      end

      <!-- Generated by model-a -->
      """

  Scenario: C4 and Sequence diagram headers are stripped
    Given models "model-a"
    And getResponse returns:
      """
      ### C4 Diagram
      ### Sequence Diagram
      ### Changes
      body
      """
    When explainPatchHelper is called
    Then it resolves to exactly:
      """


      <details>
      <summary><i>Changes</i></summary>

      ### Changes
      body
      </details>

      <!-- Generated by model-a -->
      """

  Scenario: failing models fall through to the next
    Given models "model-a model-b"
    And getResponse throws "boom" for "model-a"
    And getResponse returns "recovered"
    When explainPatchHelper is called
    Then it resolves to exactly "recovered\n</details>\n\n<!-- Generated by model-b -->"
    And the error "boom" was logged
    And the model for call 2 is "model-b"

  Scenario: models passed as a single space separated string
    Given models string "model-a model-b"
    And getResponse throws "boom" for "model-a"
    And getResponse returns "ok"
    When explainPatchHelper is called
    Then 2 calls were made
    And the model for call 1 is "model-a"
    And the model for call 2 is "model-b"
    And it resolves to exactly "ok\n</details>\n\n<!-- Generated by model-b -->"

  Scenario: all models failing rethrows the last error
    Given models "model-a model-b"
    And getResponse throws "final boom" for every model
    When explainPatchHelper is called
    Then it rejects with "final boom"

  Scenario: empty model list
    Given an empty model list
    When explainPatchHelper is called
    Then it rejects with a TypeError

  Scenario: debug logging prints the user prompt
    Given models "model-a"
    And getResponse returns "ok"
    And debug is on
    When explainPatchHelper is called
    Then the user prompt was logged

  @property
  Scenario: plain responses are wrapped deterministically
    When the plain wrap property holds for 100 runs

  @property
  Scenario: every mermaid diagram survives exactly once
    When the mermaid preservation property holds for 100 runs

  @property
  Scenario: model fallback tries models in order until one succeeds
    When the model fallback property holds for 100 runs
