import Anthropic from '@anthropic-ai/sdk';

export default async function explainPatch({patchBody, prnum, owner, repo,
  githubToken,
  model = 'claude-3-opus-20240229',
  system = `
You are an expert software engineer reviewing a pull request on Github. Lines that start with "+" have been added, lines that start with "-" have been deleted. Use markdown for formatting your review.

Desired format:
### Description
<description_of_PR> // How does this PR change the codebase? What is the motivation for this change?

### Changes
<list_of_changes> // Describe the main changes in the PR, organizing them by filename

### Security Hotspots
<list_of_security_hotspots> // Describe locations for possible vulnerabilities in the change, order by risk
\n`,
  max_tokens = 2048,
  temperature = 1,
  top_p = 1,
  debug = false}) {
  if (!patchBody) {
    const getPatch = await import('./getPatch.js');
    const patch = await getPatch.default({
      owner, repo, prnum, githubToken, debug
    });
    patchBody = patch.body;
  }

  const user_prompt = `Repository: https://github.com/${owner}/${repo}\n\nThis is the PR diff\n\`\`\`\n${patchBody}\n\`\`\``;

  if (debug) {
    console.log(`user_prompt:\n\n${user_prompt}`);
  }

  // defaults to using env variable ANTHROPIC_API_KEY
  const anthropic = new Anthropic();
  const aiResponse = await anthropic.messages.create({
    max_tokens,
    temperature,
    model,
    top_p,
    system,
    messages: [
      {
        role: 'user',
        content: user_prompt
      }
    ]
  });

  let response = aiResponse.content;

  if (debug) {
    console.log(response);
  }

  response = response[0].text.replaceAll("### Changes", "<details>\n<summary><i>Changes</i></summary>\n\n### Changes");
  response = response.replaceAll("### Security Hotspots", "</details>\n\n### Security Hotspots");
  response += `\n\n<!-- Generated by ${model} -->`;

  return response;
}
