import { parseReviewedCommit } from './utils.js'

function isOlderThanXHours (date, hours) {
  // Get the current date and time
  const now = new Date()

  // Calculate the time difference in milliseconds
  const timeDiff = now - new Date(date)

  // Convert the time difference to hours
  const timeDiffInHours = timeDiff / (1000 * 60 * 60)

  // Check if the time difference is greater than the specified number of hours
  return timeDiffInHours > hours
}

// locate the previous AI review block in the PR body with plain string
// search: begin anchor is the details header followed by our watermark,
// end anchor is the generated-by marker directly followed by the block's
// closing </details>. no dynamic RegExp (semgrep detect-non-literal-regexp)
function findReviewBlock (body, watermark) {
  const begin = '<details><summary>AI Review</summary>\n\n' + watermark
  const beginIdx = body.indexOf(begin)
  if (beginIdx === -1) return null

  const genIdx = body.indexOf('<!-- Generated by ', beginIdx + begin.length)
  if (genIdx === -1) return null

  const endAnchor = ' --></details>'
  const endIdx = body.indexOf(endAnchor, genIdx)
  if (endIdx === -1) return null

  return { start: beginIdx, end: endIdx + endAnchor.length }
}

export default async function subtleSubmitReview ({
  owner, repo, prnum, watermark, debounceTime,
  explainPatch = async () => 'no explanation provided<!-- Generated by STUB -->',
  githubToken = null,
  github = null,
  header = '',
  headSha = null,
  debug = false
}) {
  if (!github && githubToken) {
    const { Octokit } = await import('@octokit/core')

    github = new Octokit({ auth: githubToken })
  }

  if (debug) { console.log(`submitReview ${owner} ${repo} ${prnum}`) }

  if (!github && !githubToken) {
    throw new Error('You must provide a githubToken to use this function')
  }

  // check if the PR description already contains an AI review
  const query = `query($owner:String!, $name:String!, $prnumber:Int!) {
        repository(owner:$owner, name:$name) {
          pullRequest(number:$prnumber) {
            id
            body
          }
        }
    }`
  const variables = {
    owner,
    name: repo,
    prnumber: prnum
  }
  const msgPre = (await github.graphql(query, variables)).repository.pullRequest

  // skip if the PR description already contains a review for this exact commit.
  // this must run before the debounce check, which always throws when updatedAt
  // is unknown (the query does not select it)
  if (headSha && msgPre.body.includes(watermark) && parseReviewedCommit(msgPre.body) === headSha) {
    if (debug) console.log(`already reviewed commit ${headSha}`)
    return true
  }

  // debounce if the PR description contains a watermark and the debounce time is not expired yet
  if (msgPre.body.includes(watermark) && !isOlderThanXHours(msgPre.updatedAt, debounceTime)) {
    throw new Error('debounce')
  }

  // TODO: modify the PR description in place, to include the AI summarization (2 cases)
  // 1. if the PR AI description is empty, just add the AI summarization at the end
  // 2. if the PR AI description is not empty, delete the previous AI summarization and add the new one
  const newExplaination = '<details><summary>AI Review</summary>' + '\n\n' + watermark + '\n\n' + header + '\n\n' + await explainPatch() + '</details>'

  // fetch the message twice, to decrease the chances of race condition, but still debounce
  const msg = (await github.graphql(query, variables)).repository.pullRequest

  // replace the previous block in place, or append; plain string slicing so
  // replacement patterns like $& in the explanation are inserted literally
  const block = findReviewBlock(msg.body, watermark)
  const newBody = block
    ? msg.body.slice(0, block.start) + newExplaination + msg.body.slice(block.end)
    : msg.body + '\n\n' + newExplaination

  const updatePRBodyQuery = `mutation UpdatePRDescription($prId: ID!, $body: String!) {
    updatePullRequest(input:{pullRequestId:$prId, body:$body}) {
      pullRequest {
        id
        body
      }
    }
  }`
  const updateVariables = {
    prId: msg.id,
    body: newBody
  }

  await github.graphql(updatePRBodyQuery, updateVariables)
}
