export const SYSTEM_PROMPT = `
You are an expert software engineer reviewing a pull request on Github. Lines that start with "+" have been added, lines that start with "-" have been deleted. Use markdown for formatting your review.

Be terse. Technical substance exact. Only fluff die.
Drop: articles, filler words (just/really/basically/simply), pleasantries, hedging.
Fragments OK. Short synonyms preferred. Code references unchanged.
Pattern: [thing] [action] [reason].

Desired format:
### Description
<description_of_PR> // How does this PR change the codebase? What is the motivation for this change?

### Possible Issues
<list_of_issues> // Describe any other possible major non-security issues within this code. If there are none, omit this section.

### Security Hotspots
<list_of_security_hotspots> // Describe locations for possible vulnerabilities in the change, ordered by risk. Do not include a vulnerability unless it is likely to present a real security risk. If there are none, omit this section.

### Privacy Hotspots

<list_of_privacy_hotspots> // Describe locations for possible privacy issues in the change, ordered by risk. Do not include a privacy issues unless it is likely to present a real privacy risk, either in the code or in the documentation. If there are none, omit this section.

### Changes
<list_of_changes> // Describe the main changes in the PR, organizing them by filename

\`\`\`mermaid
<sequence_diagram> // Generate a sequence diagram in mermaid format for the PR included
\`\`\`
\n`

// non-global on purpose: a global regex used with .test() keeps
// lastIndex across calls and silently flips results between runs
// matches the real "### Changes" heading line only: the newline right
// after the heading rules out inline prose mentions like "`### Changes`"
// trailing spaces or CRLF line endings are tolerated
const re = /(### Changes[ \t]*\r?\n[\s\S]*?\n)###\s/
const mermaidRe = /```mermaid\n[\s\S]*?```/g

// The trivial-patch cutoff is deliberately independent of the output
// token budget: raising max_tokens must not move it or patches well
// under the new budget would silently stop being reviewed.
export const TRIVIAL_PATCH_TOKENS = 3072

// Parse an output-token limit from a 400-style "max_tokens too large"
// error (Anthropic/OpenAI APIError with status 400, Bedrock
// ValidationException). Returns the advertised limit or null when the
// error is unrelated. Only numbers below the attempted budget count as
// candidates so request ids or model names in the message cannot
// inflate the ceiling.
// Parse an output-token limit from a 400-style "max_tokens too large"
// error (Anthropic/OpenAI APIError with status 400, Bedrock
// ValidationException). Returns the advertised limit or null when the
// error is unrelated. Only numbers below the attempted budget count as
// candidates so request ids or model names in the message cannot
// inflate the ceiling. Context-length errors are rejected: they match
// the same keywords but describe the prompt, so clamping on them
// would retry at a bogus budget instead of surfacing the real error.
export function outputTokenLimit (err, budget) {
  const status = err?.status ?? err?.$metadata?.httpStatusCode
  const name = err?.name ?? ''
  if (status !== 400 && name !== 'ValidationException') return null
  const message = String(err?.message ?? '')
  if (/context (length|window)/i.test(message)) return null
  // require an explicit output-token mention so ids or model names in
  // the message cannot select the ceiling
  if (!/max_tokens|max output|output tokens|completion tokens/i.test(message)) return null
  const caps = [...message.matchAll(/\d{3,}/g)]
    .map((m) => Number(m[0]))
    .filter((n) => n >= 256 && n < budget)
  return caps.length ? Math.min(...caps) : null
}

// parse the reviewed commit sha embedded by explainPatchHelper in the
// "Generated by" marker; returns null for legacy markers without a sha.
// the model part excludes @ and > so the match can never jump past the
// first marker to a later one quoted inside the body
export function parseReviewedCommit (body) {
  const match = body.match(/<!-- Generated by [^@>]+ @ ([0-9a-f]{7,40}) -->/)
  return match ? match[1] : null
}

export async function explainPatchHelper (patchBody, owner, repo, models, debug, getResponse, headSha = null) {
  models = Array.isArray(models) ? models : models.split(' ')

  let model = null
  let response = null

  const date = new Date().toISOString().split('T')[0]
  const userPrompt = `Repository: https://github.com/${owner}/${repo}\nDate: ${date}\n\nThis is the PR diff\n\`\`\`\n${patchBody}\n\`\`\``

  if (debug) {
    console.log(`user_prompt:\n\n${userPrompt}`)
  }

  for (let i = 0; i < models.length; i++) {
    try {
      model = models[i]
      response = await getResponse(userPrompt, model)
      break
    } catch (e) {
      if (i + 1 === models.length) {
        // last model
        throw e
      }

      console.log(e)
      continue
    }
  }

  const diagrams = []
  // put diagrams inside Changes section
  for (const match of response.matchAll(mermaidRe)) {
    const diagram = match[0]
    response = response.replace(diagram, '')
    diagrams.push(diagram)
  }

  // only wrap in a details block when a Changes section exists; a
  // truncated response without one must not get a dangling closing tag
  const hasChanges = /(^|\n)### Changes\s*(\n|$)/.test(response)

  if (hasChanges) {
    // only the heading line is turned into the details opener; prose
    // mentioning "### Changes" inline must stay untouched
    response = response.replace(/(^|\n)### Changes(?=\s*\n|$)/g, '$1<details>\n<summary><i>Changes</i></summary>\n\n### Changes')

    if (re.test(response)) {
      response = response.replaceAll(/(### Changes[ \t]*\r?\n[\s\S]*?\n)###\s/g, `$1${diagrams.join('\n')}\n</details>\n\n### `)
    } else {
      response += `${diagrams.join('\n')}\n</details>`
    }
  } else if (diagrams.length > 0) {
    response += `\n${diagrams.join('\n')}`
  }

  response = response.replaceAll('### C4 Diagram', '')
  response = response.replaceAll('### Sequence Diagram', '')

  response += `\n\n<!-- Generated by ${model}${headSha ? ` @ ${headSha}` : ''} -->`
  return response
}
