name: loop bedrock
on:
  pull_request:
permissions:
  contents: read
  id-token: write
  pull-requests: write    
jobs:
  loop:
    name: loop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - run: |
          pwd
          tree -a
        shell: bash
      - uses: ./
        with:
          debug: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bedrock_aws_iam_role_arn: ${{ secrets.TEST_SECURITY_BEDROCK_AWS_IAM_ROLE_ARN }}
          region: us-west-2
          amplification: 0 # always trigger the action
