name: loop
on:
  pull_request:
jobs:
  loop:
    name: loop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - run: |
          pwd
          tree -a
        shell: bash
      - uses: ./
        with:
          debug: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
