name: puLL-Merge
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']
  merge_group:
permissions:
  contents: read
  id-token: write
  pull-requests: write
jobs:
  pull-merge:
    concurrency:
      group: ${{ github.head_ref }}-init
      cancel-in-progress: true
    name: puLL-Merge
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: brave/pull-merge@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          bedrock_aws_iam_role_arn: ${{ secrets.SECURITY_BEDROCK_AWS_IAM_ROLE_ARN }}
          region: us-west-2
