name: puLL-Merge
on:
  pull_request_target:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']
permissions:
  contents: read
  pull-requests: write
jobs:
  pull-merge:
    name: puLL-Merge
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: brave/pull-merge@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
